# wrangler.toml
name = "voiceai"                    # the name of your Worker
main = ".output/server/index.mjs"    # where Nitro spits out your server bundle
compatibility_date = "2025-06-27"    # today’s date in YYYY-MM-DD
type = "esm"                         # Nitro emits ESM modules

account_id = "224daee24e796ddf50a7bfa75d87d067"       # find this on dash.cloudflare.com > Overview
workers_dev = true                   # so you can wrangler dev without a published route

[build]
command = "npm run build"            # builds your Nuxt app (runs nuxi build)
upload = { 
  format = "service-worker",         # pick the Service Worker format
  dir = ".output/public"             # your static assets
}
